arr = [12,34,56,78,90]
arr.extend([1,2])
print(arr)
arr.sort()
print(arr)
print(len(arr))
arr.insert(0,14)
print(arr)
print(arr.count(12))
print(arr.index(56))
arr.sort(reverse=True)
print(arr)
print(14 not in arr)